Jaime tiene mareos

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('cars.csv')

In [3]:
df

,manufacturer,model,year,mileage,engine,transmission,drivetrain,fuel_type,mpg,exterior_color,interior_color,accidents_or_damage,one_owner,personal_use_only,seller_name,seller_rating,driver_rating,driver_reviews_num,price_drop,price
0,Acura,ILX Hybrid 1.5L,2013,92945.0,"1.5L I-4 i-VTEC variable valve control, engine...",Automatic,Front-wheel Drive,Gasoline,39-38,Black,Parchment,0.0,0.0,0.0,Iconic Coach,NaN,4.4,12.0,300.0,13988.0
1,Acura,ILX Hybrid 1.5L,2013,47645.0,1.5L I4 8V MPFI SOHC Hybrid,Automatic CVT,Front-wheel Drive,Hybrid,39-38,Gray,Ebony,1.0,1.0,1.0,Kars Today,NaN,4.4,12.0,NaN,17995.0
2,Acura,ILX Hybrid 1.5L,2013,53422.0,1.5L I4 8V MPFI SOHC Hybrid,Automatic CVT,Front-wheel Drive,Hybrid,39-38,Bellanova White Pearl,Ebony,0.0,1.0,1.0,Weiss Toyota of South County,4.3,4.4,12.0,500.0,17000.0
3,Acura,ILX Hybrid 1.5L,2013,117598.0,1.5L I4 8V MPFI SOHC Hybrid,Automatic CVT,Front-wheel Drive,Hybrid,39-38,Polished Metal Metallic,NaN,0.0,1.0,1.0,Apple Tree Acura,NaN,4.4,12.0,675.0,14958.0
4,Acura,ILX Hybrid 1.5L,2013,114865.0,1.5L I4 8V MPFI SOHC Hybrid,Automatic CVT,Front-wheel Drive,Hybrid,39-38,NaN,Ebony,1.0,0.0,1.0,Herb Connolly Chevrolet,3.7,4.4,12.0,300.0,14498.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
762086,Volvo,S60 B5 Momentum,2022,22877.0,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,All-wheel Drive,Gasoline,25-33,Bright Silver Metallic,Blond,0.0,1.0,0.0,Volvo Cars Danbury,4.2,4.2,2.0,250.0,34798.0
762087,Volvo,S60 T5,2012,72900.0,250.0HP 2.5L 5 Cylinder Engine Gasoline Fuel,A/T,Front-wheel Drive,Gasoline,NaN,Red,Beige,NaN,NaN,NaN,NaN,NaN,4.5,101.0,NaN,12500.0
762088,Volvo,S60 T5,2014,92000.0,2.5L I5 20V MPFI DOHC Turbo,6-Speed Automatic,Front-wheel Drive,Gasoline,21-30,Ice White,Soft Beige,0.0,0.0,1.0,Dapper Car Sales,NaN,4.8,36.0,300.0,12299.0
762089,Volvo,S60 T5 Platinum,2013,132000.0,2.5L I5 20V MPFI DOHC Turbo,6-Speed Automatic,All-wheel Drive,Gasoline,20-29,Ice White,Off Black,1.0,0.0,0.0,Legend Auto Sales Inc.,4.6,4.7,62.0,1000.0,8995.0
762090,Volvo,S60 T5 Premier,2015,115592.0,2.5L I5 20V MPFI DOHC Turbo,6-Speed Automatic,All-wheel Drive,Gasoline,20-29,Savile Gray Metallic,Off-Black,1.0,0.0,1.0,Plymouth Auto Sales,NaN,4.7,51.0,501.0,12999.0

In [ ]:
#Análisis Exploratorio

In [20]:
df['manufacturer'].value_counts()

manufacturer
Ford             79526
Toyota           59535
Chevrolet        56043
Nissan           48529
Jeep             41665
Mercedes-Benz    40824
Honda            37612
BMW              37570
Kia              35063
GMC              29563
Dodge            25250
Subaru           24767
Volkswagen       24620
Hyundai          22203
Lexus            21301
RAM              19364
Audi             17863
Cadillac         17794
Mazda            15485
Buick            14624
Chrysler         12647
INFINITI         12289
Land Rover       12272
Porsche          11461
Lincoln          10608
Volvo            10029
Acura             8489
Tesla             5883
Mitsubishi        5743
Jaguar            3469
Name: count, dtype: int64

In [ ]:
#Pasamos todos los valores de 'engine' a minúsculas.
df['engine_clean'] = df['engine'].str.lower()

In [ ]:
#Extraemos la cilindrada (litros)
import re

def extract_liters(x):
    if pd.isna(x):
        return None
    match = re.search(r'(\d\.\d|\d)\s*l', x)
    if match:
        return float(match.group(1))
    return None

df['engine_liters'] = df['engine_clean'].apply(extract_liters)

In [ ]:
#Extraemos el número de cilindridos
def extract_cylinders(x):
    if pd.isna(x):
        return None
    match = re.search(r'(v|i|l)(\d)', x)
    if match:
        return int(match.group(2))
    return None

df['engine_cylinders'] = df['engine_clean'].apply(extract_cylinders)

In [ ]:
#Extraer tipo de motor
def extract_engine_type(x):
    if pd.isna(x):
        return "unknown"
    if "turbo" in x or "t" in x:
        return "turbo"
    if "super" in x:
        return "supercharged"
    if "electric" in x:
        return "electric"
    if "hybrid" in x:
        return "hybrid"
    return "natural"

df['engine_type'] = df['engine_clean'].apply(extract_engine_type)

In [ ]:
#Si engine es electric: litros=0; cilindros=0
#Si creamos estas 3 columnas para diferenciar realmente entre la cilindrada, el número de cilindros y el tipo de motor podemos eliminar posteriormente 'engine_clean':
#df.drop(columns=['engine_clean'], inplace=True)

In [4]:
df['year'].min(), df['year'].max()

(1915, 2024)

MILEAGE

In [ ]:
#El kilometraje del coche es muy importante. Para los valores ausentes, podemos imputar la mediana por grupo teniendo en cuenta manufacturer + model + year

ENGINE

In [ ]:
#Rellenar con una categoría “unknown” ANTES de aplicar las funciones de limpieza.

TRANSMISSION

Aquí vamos a dividir esta columna en 3 categorías

In [ ]:
# df['transmission_clean'] = df['transmission'].astype(str).str.lower()

# def simplify_transmission(x):
#     if pd.isna(x):
#         return "unknown"
    
#     # AUTOMÁTICAS
#     if any(word in x for word in [
#         "auto", "cvt", "dct", "dual", "tiptronic", "dsg", "shift"
#     ]):
#         return "automatic"
    
#     # MANUALES
#     if "manual" in x or "man " in x or " 5mt" in x or " 6mt" in x:
#         return "manual"
    
#     return "other"

# df['transmission'] = df['transmission_clean'].apply(simplify_transmission)
# df = df.drop(columns=['transmission_clean'])

In [6]:
df

,manufacturer,model,year,mileage,engine,transmission,drivetrain,fuel_type,mpg,exterior_color,...,one_owner,personal_use_only,seller_name,seller_rating,driver_rating,driver_reviews_num,price_drop,price,transmission_clean,transmission_simple
0,Acura,ILX Hybrid 1.5L,2013,92945.0,"1.5L I-4 i-VTEC variable valve control, engine...",Automatic,Front-wheel Drive,Gasoline,39-38,Black,...,0.0,0.0,Iconic Coach,NaN,4.4,12.0,300.0,13988.0,automatic,automatic
1,Acura,ILX Hybrid 1.5L,2013,47645.0,1.5L I4 8V MPFI SOHC Hybrid,Automatic CVT,Front-wheel Drive,Hybrid,39-38,Gray,...,1.0,1.0,Kars Today,NaN,4.4,12.0,NaN,17995.0,automatic cvt,automatic
2,Acura,ILX Hybrid 1.5L,2013,53422.0,1.5L I4 8V MPFI SOHC Hybrid,Automatic CVT,Front-wheel Drive,Hybrid,39-38,Bellanova White Pearl,...,1.0,1.0,Weiss Toyota of South County,4.3,4.4,12.0,500.0,17000.0,automatic cvt,automatic
3,Acura,ILX Hybrid 1.5L,2013,117598.0,1.5L I4 8V MPFI SOHC Hybrid,Automatic CVT,Front-wheel Drive,Hybrid,39-38,Polished Metal Metallic,...,1.0,1.0,Apple Tree Acura,NaN,4.4,12.0,675.0,14958.0,automatic cvt,automatic
4,Acura,ILX Hybrid 1.5L,2013,114865.0,1.5L I4 8V MPFI SOHC Hybrid,Automatic CVT,Front-wheel Drive,Hybrid,39-38,NaN,...,0.0,1.0,Herb Connolly Chevrolet,3.7,4.4,12.0,300.0,14498.0,automatic cvt,automatic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
762086,Volvo,S60 B5 Momentum,2022,22877.0,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,All-wheel Drive,Gasoline,25-33,Bright Silver Metallic,...,1.0,0.0,Volvo Cars Danbury,4.2,4.2,2.0,250.0,34798.0,8-speed automatic,automatic
762087,Volvo,S60 T5,2012,72900.0,250.0HP 2.5L 5 Cylinder Engine Gasoline Fuel,A/T,Front-wheel Drive,Gasoline,NaN,Red,...,NaN,NaN,NaN,NaN,4.5,101.0,NaN,12500.0,a/t,other
762088,Volvo,S60 T5,2014,92000.0,2.5L I5 20V MPFI DOHC Turbo,6-Speed Automatic,Front-wheel Drive,Gasoline,21-30,Ice White,...,0.0,1.0,Dapper Car Sales,NaN,4.8,36.0,300.0,12299.0,6-speed automatic,automatic
762089,Volvo,S60 T5 Platinum,2013,132000.0,2.5L I5 20V MPFI DOHC Turbo,6-Speed Automatic,All-wheel Drive,Gasoline,20-29,Ice White,...,0.0,0.0,Legend Auto Sales Inc.,4.6,4.7,62.0,1000.0,8995.0,6-speed automatic,automatic
762090,Volvo,S60 T5 Premier,2015,115592.0,2.5L I5 20V MPFI DOHC Turbo,6-Speed Automatic,All-wheel Drive,Gasoline,20-29,Savile Gray Metallic,...,0.0,1.0,Plymouth Auto Sales,NaN,4.7,51.0,501.0,12999.0,6-speed automatic,automatic