## NOTEBOOK JAIME ANÁLISIS EXPLORATORIO (fuel_type - personal_use_only)

In [1]:
import pandas as pd

In [ ]:
df = pd.read_csv('../data/raw/cars.csv')

In [5]:
df

,manufacturer,model,year,mileage,engine,transmission,drivetrain,fuel_type,mpg,exterior_color,interior_color,accidents_or_damage,one_owner,personal_use_only,seller_name,seller_rating,driver_rating,driver_reviews_num,price_drop,price
0,Acura,ILX Hybrid 1.5L,2013,92945.0,"1.5L I-4 i-VTEC variable valve control, engine...",Automatic,Front-wheel Drive,Gasoline,39-38,Black,Parchment,0.0,0.0,0.0,Iconic Coach,NaN,4.4,12.0,300.0,13988.0
1,Acura,ILX Hybrid 1.5L,2013,47645.0,1.5L I4 8V MPFI SOHC Hybrid,Automatic CVT,Front-wheel Drive,Hybrid,39-38,Gray,Ebony,1.0,1.0,1.0,Kars Today,NaN,4.4,12.0,NaN,17995.0
2,Acura,ILX Hybrid 1.5L,2013,53422.0,1.5L I4 8V MPFI SOHC Hybrid,Automatic CVT,Front-wheel Drive,Hybrid,39-38,Bellanova White Pearl,Ebony,0.0,1.0,1.0,Weiss Toyota of South County,4.3,4.4,12.0,500.0,17000.0
3,Acura,ILX Hybrid 1.5L,2013,117598.0,1.5L I4 8V MPFI SOHC Hybrid,Automatic CVT,Front-wheel Drive,Hybrid,39-38,Polished Metal Metallic,NaN,0.0,1.0,1.0,Apple Tree Acura,NaN,4.4,12.0,675.0,14958.0
4,Acura,ILX Hybrid 1.5L,2013,114865.0,1.5L I4 8V MPFI SOHC Hybrid,Automatic CVT,Front-wheel Drive,Hybrid,39-38,NaN,Ebony,1.0,0.0,1.0,Herb Connolly Chevrolet,3.7,4.4,12.0,300.0,14498.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
762086,Volvo,S60 B5 Momentum,2022,22877.0,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,All-wheel Drive,Gasoline,25-33,Bright Silver Metallic,Blond,0.0,1.0,0.0,Volvo Cars Danbury,4.2,4.2,2.0,250.0,34798.0
762087,Volvo,S60 T5,2012,72900.0,250.0HP 2.5L 5 Cylinder Engine Gasoline Fuel,A/T,Front-wheel Drive,Gasoline,NaN,Red,Beige,NaN,NaN,NaN,NaN,NaN,4.5,101.0,NaN,12500.0
762088,Volvo,S60 T5,2014,92000.0,2.5L I5 20V MPFI DOHC Turbo,6-Speed Automatic,Front-wheel Drive,Gasoline,21-30,Ice White,Soft Beige,0.0,0.0,1.0,Dapper Car Sales,NaN,4.8,36.0,300.0,12299.0
762089,Volvo,S60 T5 Platinum,2013,132000.0,2.5L I5 20V MPFI DOHC Turbo,6-Speed Automatic,All-wheel Drive,Gasoline,20-29,Ice White,Off Black,1.0,0.0,0.0,Legend Auto Sales Inc.,4.6,4.7,62.0,1000.0,8995.0
762090,Volvo,S60 T5 Premier,2015,115592.0,2.5L I5 20V MPFI DOHC Turbo,6-Speed Automatic,All-wheel Drive,Gasoline,20-29,Savile Gray Metallic,Off-Black,1.0,0.0,1.0,Plymouth Auto Sales,NaN,4.7,51.0,501.0,12999.0

## ANALISIS EXPLORATORIO (fuel_type, mpg, exterior_color, interior_color, accidents_or_damage, one_owner, personal_use_only)

In [7]:
df_jaime = df[['fuel_type', 'mpg', 'exterior_color', 'interior_color', 'accidents_or_damage', 'one_owner', 'personal_use_only']]

In [8]:
df_jaime

,fuel_type,mpg,exterior_color,interior_color,accidents_or_damage,one_owner,personal_use_only
0,Gasoline,39-38,Black,Parchment,0.0,0.0,0.0
1,Hybrid,39-38,Gray,Ebony,1.0,1.0,1.0
2,Hybrid,39-38,Bellanova White Pearl,Ebony,0.0,1.0,1.0
3,Hybrid,39-38,Polished Metal Metallic,NaN,0.0,1.0,1.0
4,Hybrid,39-38,NaN,Ebony,1.0,0.0,1.0
...,...,...,...,...,...,...,...
762086,Gasoline,25-33,Bright Silver Metallic,Blond,0.0,1.0,0.0
762087,Gasoline,NaN,Red,Beige,NaN,NaN,NaN
762088,Gasoline,21-30,Ice White,Soft Beige,0.0,0.0,1.0
762089,Gasoline,20-29,Ice White,Off Black,1.0,0.0,0.0
762090,Gasoline,20-29,Savile Gray Metallic,Off-Black,1.0,0.0,1.0

## fuel_type

In [9]:
df_jaime['fuel_type'].unique()

array(['Gasoline', 'Hybrid', nan, 'Premium', 'Electric',
       'Gasoline/Mild Electric Hybrid', 'Diesel', 'E85 Flex Fuel',
       'Flexible Fuel', 'Gasoline Fuel', 'Plug-In Hybrid',
       'Premium (Required)', 'Regular Unleaded', 'Unspecified', 'Unknown',
       'Compressed Natural Gas', 'Other', 'Natural Gas', 'Gaseous',
       'Bi-Fuel', 'Flex Fuel Capability', 'Diesel Fuel',
       'Premium Unleaded', 'Biodiesel', 'Bio Diesel',
       'Hydrogen Fuel Cell', 'Gas', 'PHEV', 'Hybrid Fuel', 'Automatic',
       'E85 Fl', 'Electric Fuel System', 'G', 'B', 'Gas/Electric Hybrid',
       'Flex Fuel', 'Plug-In Electric/Gas'], dtype=object)

In [10]:
df_jaime['fuel_type'].isna().sum()

np.int64(22927)

## mpg
tenemos la columna en rangos; min-max, sería recomendable pasarlo a un solo número utilizando la media. Y tenemos en millas/galón, pasandolo a un solo numero si podriamos comvertirlo en litros/100km (df['L_per_100km'] = 235.214 / df['mpg']).

In [21]:
df_jaime['mpg'].isna().sum()

np.int64(142071)

## exterior_color

In [11]:
df_jaime['exterior_color'].unique()

array(['Black', 'Gray', 'Bellanova White Pearl', ...,
       'White Blndchr Vinyl', 'Osmin Gray Metallic', 'COL01900'],
      shape=(7682,), dtype=object)

In [12]:
df_jaime['exterior_color'].isna().sum()

np.int64(8859)

## interior_color

In [13]:
df_jaime['interior_color'].unique()

array(['Parchment', 'Ebony', nan, ..., 'Blond Charcoal Vinyl',
       'Blondlrettech', 'Atacama'], shape=(4680,), dtype=object)

In [14]:
df_jaime['interior_color'].isna().sum()

np.int64(56975)

## accidents_or_damage

In [17]:
df_jaime['accidents_or_damage'].isna().sum()

np.int64(24212)

#### 3% missings

In [16]:
df_jaime['accidents_or_damage'].value_counts()

accidents_or_damage
0.0    569188
1.0    168691
Name: count, dtype: int64

## one_owner

In [18]:
df_jaime['one_owner'].value_counts()

one_owner
1.0    410579
0.0    320029
Name: count, dtype: int64

#### 1 = Solo un dueño
#### 0 = Más de un dueño

## personal_use_only

In [19]:
df_jaime['personal_use_only'].value_counts()

personal_use_only
1.0    484522
0.0    252717
Name: count, dtype: int64

#### 1 = Uso personal

#### 0 = No solo uso personal

In [20]:
df_jaime['personal_use_only'].isna().sum()

np.int64(24852)

#### 3% missings